# CICD Runner golangci-lint Configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

# ===========================================================================
# Run Configuration
# ===========================================================================
run:
  go: "1.23"
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  concurrency: 4

# ===========================================================================
# Linters Configuration
# ===========================================================================
linters:
  default: none
  enable:
    # Static analysis (core)
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign

    # Additional linters
    - errorlint
    - prealloc
    - bodyclose
    - gocritic
    - misspell
    - nilerr
    - gosec

  # Linter-specific settings
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    errcheck:
      check-type-assertions: true
      check-blank: true

    gosec:
      excludes:
        - G104
        - G307
        - G301
        - G204
        - G107
        - G304
        - G306
        - G115  # Allow int->uint conversion for size values

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - unnamedResult
        - ifElseChain
        - commentedOutCode
        - unnecessaryDefer
        - appendCombine
        - paramTypeCombine
        - importShadow
        - exitAfterDefer      # Allow os.Exit in main after defer
        - httpNoBody         # nil body is idiomatic for GET requests
        - emptyStringTest    # Existing code is readable
        - octalLiteral       # Old style is acceptable
        - regexpSimplify     # Existing regex is readable
        - nestingReduce      # Existing code is readable
        - elseif             # else {if } style is acceptable

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    misspell:
      locale: US

  # Exclusion rules (v2 format)
  exclusions:
    # Exclude generated files
    generated: lax

    # Exclude paths
    paths:
      - build
      - dist
      - vendor
      - testdata
      - examples
      - ".*\\.gen\\.go$"
      - ".*\\.mock\\.go$"
      - ".*_string\\.go$"

    # Exclusion rules
    rules:
      # Test files: relax error checking
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - bodyclose
          - nilerr
          - prealloc
          - unconvert
          - unused
          - govet
          - staticcheck
          - gocritic
          - misspell

      # MCP generated code
      - path: pkg/mcp/
        linters:
          - errcheck
          - gosec
          - gocritic

      # Platform integration code - uses external API naming
      - path: pkg/platform/gitee_webhook\.go
        linters:
          - misspell

      # Platform client code - many cleanup patterns
      - path: pkg/platform/
        linters:
          - errcheck
          - gosec

      # Observability - cleanup code
      - path: pkg/observability/
        linters:
          - errcheck
          - gosec

      # Perf utilities - type assertions
      - path: pkg/perf/
        linters:
          - errcheck

      # Kill/skill module - cleanup and error handling
      - path: pkg/skill/
        linters:
          - errcheck
          - misspell
          - gocritic

      # Runner cache - MD5 for file hashing (acceptable for cache keys)
      - path: pkg/runner/cache\.go
        linters:
          - gosec
          - errcheck
          - gocritic

      # Security sandbox - syscall usage and resource limits
      - path: pkg/security/sandbox\.go
        linters:
          - errcheck
          - gosec

      # AI/Claude code - parser errors
      - path: pkg/ai/
        linters:
          - errcheck
          - gocritic

      # Main command - context cancellation
      - path: cmd/cicd-runner/
        linters:
          - misspell

      # Platform status - external API naming
      - path: pkg/platform/gitee_status\.go
        linters:
          - misspell

      # Platform github - empty branch in error cleanup
      - path: pkg/platform/github\.go
        linters:
          - staticcheck

      # Workerpool - empty branch in panic recovery
      - path: pkg/perf/workerpool\.go
        linters:
          - staticcheck

      # Perf cache - embedded field access pattern
      - path: pkg/perf/cache\.go
        linters:
          - staticcheck

      # Security sandbox - type assertion for exec.ExitError
      - path: pkg/security/sandbox\.go
        linters:
          - errorlint

      # Security injection test - type assertion for test errors
      - path: pkg/security/injection_test\.go
        linters:
          - errorlint

      # Claude parser - regex pattern and parsing
      - path: pkg/claude/parser\.go
        linters:
          - errcheck
          - gocritic

      # Claude pool - home directory fallback
      - path: pkg/claude/pool\.go
        linters:
          - errcheck

      # Claude session - cleanup error handling
      - path: pkg/claude/session_impl\.go
        linters:
          - errcheck

      # AI claude - session cleanup
      - path: pkg/ai/claude\.go
        linters:
          - errcheck

# ===========================================================================
# Formatters Configuration
# ===========================================================================
formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - build
      - dist
      - vendor

# ===========================================================================
# Output Configuration
# ===========================================================================
output:
  formats:
    text:
      path: stdout
      colors: true
  sort-results: true
  sort-order:
    - linter
    - file
