name: 'AI Test Generator'
description: 'Generate unit tests based on code changes'
author: 'cicd-ai-toolkit'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  target-path:
    description: 'Path to generate tests for (default: all changes)'
    required: false
    default: ''
  test-framework:
    description: 'Test framework to use (auto, jest, pytest, go-test)'
    required: false
    default: 'auto'
  create-pr:
    description: 'Create PR with generated tests'
    required: false
    default: 'true'
  pr-branch-prefix:
    description: 'Branch name prefix for test PRs'
    required: false
    default: 'ai-tests/'
  config:
    description: 'Path to configuration file'
    required: false
    default: '.cicd-ai-toolkit.yaml'

outputs:
  tests-generated:
    description: 'Number of test files generated'
    value: ${{ steps.run.outputs.count }}
  pr-url:
    description: 'URL of created PR (if applicable)'
    value: ${{ steps.pr.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Generate Tests
      id: run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "::group::Generating Tests"
        cicd-runner run \
          --skills test-generator \
          --target-path "${{ inputs.target-path }}" \
          --test-framework "${{ inputs.test-framework }}" \
          --config "${{ inputs.config }}" \
          --output-dir /tmp/generated-tests

        COUNT=$(find /tmp/generated-tests -type f \( -name '*.test.*' -o -name '*_test.*' \) 2>/dev/null | wc -l | tr -d ' ')
        echo "count=$COUNT" >> $GITHUB_OUTPUT
        echo "Generated $COUNT test files"
        echo "::endgroup::"

    - name: Commit tests
      id: commit
      if: inputs.create-pr == 'true' && steps.run.outputs.count != '0'
      shell: bash
      run: |
        # Validate branch prefix (allow only safe characters)
        PREFIX="${{ inputs.pr-branch-prefix }}"
        if [[ ! "$PREFIX" =~ ^[A-Za-z0-9._/-]*$ ]]; then
          echo "::error::Invalid pr-branch-prefix: contains unsafe characters"
          exit 1
        fi

        git config user.name "cicd-ai-toolkit[bot]"
        git config user.email "ai@cicd-toolkit.dev"

        BRANCH="${PREFIX}$(date +%s)"

        # Create branch from clean remote baseline
        git fetch origin
        git checkout -b "$BRANCH" "origin/${{ github.ref_name }}"

        # Copy and add only generated test files
        cp -r /tmp/generated-tests/* .
        find /tmp/generated-tests -type f | while read -r f; do
          rel_path="${f#/tmp/generated-tests/}"
          git add "$rel_path"
        done

        git commit -m "feat(test): generate unit tests

        Generated by cicd-ai-toolkit
        Tests: ${{ steps.run.outputs.count }} files"

        git push origin "$BRANCH"
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT

    - name: Create PR
      id: pr
      if: inputs.create-pr == 'true' && steps.run.outputs.count != '0'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        PR_URL=$(gh pr create \
          --title "feat(test): AI-generated unit tests (${{ steps.run.outputs.count }} files)" \
          --body "## Summary

        Automatically generated unit tests by cicd-ai-toolkit.

        **Files generated:** ${{ steps.run.outputs.count }}

        ---
        _Generated by [cicd-ai-toolkit](https://github.com/cicd-ai-toolkit/cicd-ai-toolkit)_" \
          --base ${{ github.ref_name }} \
          --head "${{ steps.commit.outputs.branch }}")

        echo "url=$PR_URL" >> $GITHUB_OUTPUT
        echo "Created PR: $PR_URL"
